# https://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

THRESHOLD = 4000000

n0 = 0
n1 = 1
n2 = 0
accum = 0

until accum > THRESHOLD
	n2 = n1 + n0
	n0 = n1
	n1 = n2
	accum += n2 if n2.even?
end

puts accum # 4613732
